### ISSUE TITLE
read ECONNRESET

### ISSUE THREAD

**Issue by skyfsj** [bangbang93/minecraft-proxy#70]
下游服务端：forge-1.19.2-43.2.8
代理服务器版本：v1.5.0
代理服务器配置：
```yml
proxy:
  port: 25565
  host: 0.0.0.0
  workers: 0
defaultServer: mod1
allowListOnly: false
allowList:
  ips: ["0.0.0.0/0"]
  usernames:
    - CN_NKXingCh
  uuids: []
blockList:
  ips: !!import/single block-ip.yml
  usernames:
    - BadGays
  uuids:
    - 12b8b9e0eba0ca37e935f037ff1ae90d
servers:
  !!import/sequence
  - servers/
profileEndpoint: https://skin.pigeon-server.cn/api/yggdrasil/api/profiles/minecraft
message:
  bannedUsername: "未授权用户"
  bannedUUID: "未授权用户"
loglevel: info # 'trace', 'debug', 'info', 'warn', 'error', 'fatal'

serverName: mod1
proxyHost: 192.168.1.2
proxyPort: 25566
version: 1.19.2
handlePing: false
onlineMode: true

```
代理服务器日志：
```log
{"name":"client","hostname":"DESKTOP-ERJEJGM","pid":15476,"remoteAddress":"127.0.0.1","remotePort":61944,"username":"fsj","backend":{"host":"192.168.1.2","port":25566},"level":30,"msg":"force disconnecting, reason: failed to connect backend: read ECONNRESET","time":"2023-05-18T12:51:17.811Z","v":0}
{"name":"server","port":25565,"host":"0.0.0.0","worker":8,"hostname":"DESKTOP-ERJEJGM","pid":15476,"level":50,"err":{"errno":-4077,"code":"ECONNRESET","syscall":"read"},"msg":"read ECONNRESET","time":"2023-05-18T12:51:17.812Z","v":0}
```

客户端输出：
![image](https://github.com/bangbang93/minecraft-proxy/assets/47785500/3dce2fdd-615b-4568-af02-0604f666833c)
